@ExamCore.Api_HostAddress = https://localhost:7106

GET {{ExamCore.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ExamCore.Api_HostAddress}}/api/role/CreateAsync
Content-Type: application/json

{
  "Name": "Manager"
}

###
